### ISSUE TITLE
入力フォーム

### ISSUE THREAD

**Issue by NamikawaRyotaro** [m47ch4n/liar-game-tut2020#2]
行きたい研究室(プルダウン)
自分の成績(S-A-B-C-Dのプルダウン)

これ以外に必要なものないよね？

**Comment by m47ch4n** [comment]
いいと思います。
任意の名前を設定できるかについては、みんなの意見に委ねる。

**Comment by NamikawaRyotaro** [comment]
諸々の修正につき削除
